name: amazon
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  country_picker: ^2.0.21
  firebase_auth: ^4.11.0
  firebase_core: ^2.18.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.2
  page_transition: ^2.1.0
  provider: ^6.0.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/amazon_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
